comment:
  image:
    repository: vasiilij/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: vasiilij/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: vasiilij/ui
    tag: latest
  service:
    externalPort: 9292

mongodb:
  usePassword: false
