FROM alpine:3.14.0

RUN apk add --update --no-cache ruby-full ruby-dev alpine-sdk \
    && gem install bundler:1.17.3

ENV APP_HOME /app

WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
