FROM alpine:3.14.0

RUN apk add --update --no-cache ruby-full ruby-dev alpine-sdk \
    && gem install bundler:1.17.3

ENV APP_HOME /app

WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
