version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:${MONGO_DB_PATH}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      prometheus_net:

  ui:
    image: ${USER_NAME}/ui:${UI_TAG}
    ports:
      - "${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp"
    networks:
      - front_net
      - prometheus_net

  post:
    image: ${USER_NAME}/post:${POST_TAG}
    networks:
      - back_net
      - front_net
      - prometheus_net

  comment:
    image: ${USER_NAME}/comment:${COMMENT_TAG}
    networks:
      - back_net
      - front_net
      - prometheus_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
  prometheus_net:
