version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:${MONGO_DB_PATH}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      prometheus_net:

  ui:
    image: ${USER_NAME}/ui:${UI_TAG}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp"
    networks:
      - front_net
      - prometheus_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_TAG}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - back_net
      - front_net
      - prometheus_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_TAG}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
      - prometheus_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
  prometheus_net:
