{
 "title": "Telegraf metrics",
 "description": "Prometheus/victoriametrics dashboards for telegraf metrics",
 "tags": [
  "prometheus",
  "telegraf",
  "victoriametrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": "label_values(host)" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "docker_container_cpu_usage_percent",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}",
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_cpu\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  { "title": "DOCKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RAM usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "col": "usage",
     "expr": "docker_container_mem_usage_percent",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}",
     "measurement": "docker_container_mem",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network usage by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes[1m])"
    }
   ]
  },
  {
   "title": "Network packets by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "abs(docker_container_net_tx_packets)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_packets" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network dropped by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "tx",
     "expr": "abs(docker_container_net_tx_dropped)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: tx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_dropped\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "tx_dropped" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Network errors by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "col": "rx",
     "expr": "abs(docker_container_net_rx_errors)",
     "groupBy": " by (host,container_image)",
     "legendFormat": "{{host}}: {{container_image}}: rx",
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_errors\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  host =~ /$server$/ AND $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  }
 ]
}