---
required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - unzip

# DOCKER
docker_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
docker_user: ubuntu
docker_group: docker

# K8S
k8s_required_packages:
  - apt-transport-https
  - ca-certificates
  - curl

cni_calico_ipv4pool_cidr: 10.244.0.0/16
k8s_regular_user: ubuntu

k8s_apiserver_cert_extra_sans: "{{ ansible_host }}"
k8s_apiserver_advertise_address: "0.0.0.0"
k8s_control_plane_endpoint: "{{ ansible_host }}"
k8s_pod_network_cidr: 10.244.0.0/16
k8s_regular_user: "{{ ansible_user }}"

k8s_signing_key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
k8s_repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
k8s_packages:
  - kubelet
  - kubeadm
  - kubectl
k8s_user: ubuntu
