---
- name: Install Docker Engine
  debug:
    msg: "Installing Docker Engine ..."

- name: Update repositories cache and install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "172800"
  loop: "{{ required_packages }}"

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_repo_key_url }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: "172800"

- name: Install docker packages
  apt:
    pkg: "{{ item }}"
  loop: "{{ docker_packages }}"

- name: Ensure user added to the docker group.
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: true
