version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:${MONGO_DB_PATH}
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - "${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp"
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_TAG}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
